package com.nmssaveexplorer.registry;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

/**
 * generated by the Python script
 * Loads {@code localisation_map.json} and exposes
 * item definitions containing display names and icon paths.
 */
public final class ItemDefinitionRegistry {

    private static final String RESOURCE_PATH = "/localisation_map.json";
    private static final Map<String, ItemDefinition> DEFINITIONS = new HashMap<>();
    private static volatile boolean initialised = false;

    private ItemDefinitionRegistry() {
    }

    private static void ensureLoaded() {
        if (initialised) {
            return;
        }
        synchronized (ItemDefinitionRegistry.class) {
            if (initialised) {
                return;
            }
            loadDefinitions();
            initialised = true;
        }
    }

    private static void loadDefinitions() {
        try (InputStream stream = ItemDefinitionRegistry.class.getResourceAsStream(RESOURCE_PATH)) {
            if (stream == null) {
                System.err.println("[ItemDefinitionRegistry] Missing resource: " + RESOURCE_PATH);
                return;
            }

            JsonObject root = JsonParser.parseReader(new InputStreamReader(stream, StandardCharsets.UTF_8))
                    .getAsJsonObject();
            for (Map.Entry<String, JsonElement> entry : root.entrySet()) {
                if (!entry.getValue().isJsonObject()) {
                    continue;
                }
                JsonObject obj = entry.getValue().getAsJsonObject();
                String name = obj.has("name") ? obj.get("name").getAsString() : null;
                String icon = obj.has("icon") ? obj.get("icon").getAsString() : null;
                if ((name == null || name.isEmpty()) && (icon == null || icon.isEmpty())) {
                    continue;
                }
                String key = entry.getKey().toUpperCase(Locale.ROOT);
                DEFINITIONS.put(key, new ItemDefinition(name, icon));
            }
            System.out.println("[ItemDefinitionRegistry] Loaded entries: " + DEFINITIONS.size());
        } catch (Exception ex) {
            System.err.println("[ItemDefinitionRegistry] Failed to load " + RESOURCE_PATH + ": " + ex.getMessage());
        }
    }

    public static ItemDefinition getDefinition(String itemId) {
        if (itemId == null || itemId.isEmpty()) {
            return null;
        }
        ensureLoaded();
        String key = normaliseKey(itemId);
        ItemDefinition definition = DEFINITIONS.get(key);
        if (definition != null) {
            return definition;
        }
        String fallbackKey = deriveFallbackKey(key);
        return (fallbackKey != null) ? DEFINITIONS.get(fallbackKey) : null;
    }

    public static String getDisplayName(String itemId) {
        ItemDefinition definition = getDefinition(itemId);
        return definition != null ? definition.name() : null;
    }

    public static Map<String, ItemDefinition> getAllDefinitions() {
        ensureLoaded();
        return Collections.unmodifiableMap(DEFINITIONS);
    }

    private static String normaliseKey(String itemId) {
        String key = itemId.startsWith("^") ? itemId.substring(1) : itemId;
        int hashIndex = key.indexOf('#');
        if (hashIndex >= 0) {
            key = key.substring(0, hashIndex);
        }
        return key.toUpperCase(Locale.ROOT);
    }

    private static String deriveFallbackKey(String key) {
        if (key.startsWith("UP_") && key.length() > 3) {
            return "U_" + key.substring(3);
        }
        return null;
    }

    public record ItemDefinition(String name, String icon) {}
}
